fix(dbm-services): 忽略采集windows主机的空磁盘 #6800

diff --git a/.github/workflows/go_code_check.yml b/.github/workflows/go_code_check.yml
--- a/.github/workflows/go_code_check.yml
+++ b/.github/workflows/go_code_check.yml
@@ -16,25 +16,25 @@ jobs:
     name: Build and Lint
     runs-on: ubuntu-20.04
     steps:
-    - name: Setup Go
-      uses: actions/setup-go@v2
-      with:
-        go-version: 1.19
-    - name: Install goimports
-      run: go install golang.org/x/tools/cmd/goimports@latest
-    - name: Check code
-      uses: actions/checkout@v4
-    - run: goimports -w .
-    - name: Run go mod tidy on all modules
-      run: find . -name go.mod -execdir go mod tidy \;
-    # If there are any diffs from goimports or go mod tidy, fail.
-    - name: Verify no changes from goimports and go mod tidy.
-      run: |
-        if [ -n "$(git status --porcelain)" ]; then
-          echo 'To fix this check, run "goimports -w . && find . -name go.mod -execdir go mod tidy \;"'
-          git status # Show the files that failed to pass the check.
-          exit 1
-        fi
+      - name: Setup Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: 1.19
+      - name: Install goimports
+        run: go install golang.org/x/tools/cmd/goimports@v0.24.0
+      - name: Check code
+        uses: actions/checkout@v4
+      - run: goimports -w .
+      - name: Run go mod tidy on all modules
+        run: find . -name go.mod -execdir go mod tidy \;
+      # If there are any diffs from goimports or go mod tidy, fail.
+      - name: Verify no changes from goimports and go mod tidy.
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo 'To fix this check, run "goimports -w . && find . -name go.mod -execdir go mod tidy \;"'
+            git status # Show the files that failed to pass the check.
+            exit 1
+          fi
 
 # TODO
 #    - name: go vet
